# (C) British Crown Copyright 2025, Met Office.
# Please see LICENSE.md for license details.

name: "Process new metadata entry"
on: 
  issues:
    types: [opened, edited]

jobs:
  process-metadata:
    if: contains(github.event.issue.labels.*.name, 'metadata_entry')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v3

      - name: block closed issues
        if: github.event.issue.state == 'closed'
        run: |
          gh issue comment "$NUMBER" --body "$BODY"
          echo "NOTE: The issue is currently closed. A new issue must be opened in order to process any changes."
          exit 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            You are attempting to edit a closed issue. A new issue must be opened in order to process any changes.
            Your edits have **not** been processed.
        
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: install dependencies
        run: |
          pip install "metomi-isodatetime==1!3.0.0"
          pip install "requests==2.34.2"
        
      - name: create metadata file
        id: create-file
        env:
          ISSUE_BODY: |
              ${{ github.event.issue.body }}
          # pipe preseves newline properties for multilines
        run: python scripts/create_metadata_conf.py
        continue-on-error: true

      - name: return issues to user
        id: check-issues
        if: steps.create-file.outcome == 'failure'
        run: |
          gh issue comment "$NUMBER" --body "$BODY"
          echo "NOTE: Script failure has occured due to user input error. The user has been notified and instructed to 
          resubmit a corrected form. No further action required..."
          echo "input_error=true" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            Your metadata file contains incorrect or improperly formatted fields. 
            Please re submit your form and amend the following issues:
            ${{ steps.create-file.outputs.warnings }}.

            If you believe this to be an error, please contact a member of the CDDS team.

            Thank you for your contribution.

      - name: check if file exists
        if: steps.check-issues.outputs.input_error != 'true'
        id: exists
        run: |
          if git ls-tree -r HEAD --name-only | grep -q "${{ steps.create-file.outputs.filename }}"; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "exists=true"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "exists=false"
          fi

      - name: generate variable list
        if: steps.exists.outputs.exists == 'false' && steps.check-issues.outputs.input_error != 'true'
        id: generate-variable-list
        env:
          ISSUE_BODY: |
              ${{ github.event.issue.body }}
        run: |
          python scripts/generate_variable_lists.py
        continue-on-error: true

      - name: warn of missing variable list
        if: steps.generate-variable-list.outcome == 'failure' && steps.create-file.outcome == 'success'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git add *.cfg
          git commit -m "New workflow metadata file added from issue #${{ github.event.issue.number }}"
          git push origin main

          gh issue comment "$ISSUE" --body "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ISSUE: ${{ github.event.issue.number }}
          BODY: >
            Your metadata file has been successfully added to the repository as ${{ steps.create-file.outputs.filename }}, however we were unable to generate a corresponding variable list for this workflow.
            Please contact a member of the CDDS team so that we can investigate.

            Please DO NOT close this issue unless advised by a member of the CDDS team. 

      - name: commit new file and close issue
        if: steps.exists.outputs.exists == 'false' && steps.check-issues.outputs.input_error != 'true' && steps.generate-variable-list.outcome == 'success'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git add *.cfg *.txt
          git commit -m "New workflow metadata file added from issue #${{ github.event.issue.number }}"
          git push origin main

          gh issue comment "$ISSUE" --body "$BODY"
          gh issue close --repo "$REPO" "$ISSUE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ISSUE: ${{ github.event.issue.number }}
          BODY: >
            Your metadata file has been successfully added to the repository as: 
            ${{ steps.create-file.outputs.filename }}

            A corresponding variable list has also been created for you as:
            ${{ steps.generate-variable-list.outputs.filename }}

            If you would like to generate a CDDS request configuration file, please fill out the issue form titled 'Request The Generation Of A CDDS Request File'.

            Thank you for your contribution.
          
      - name: check diff
        id: diff
        if: steps.exists.outputs.exists == 'true' && steps.check-issues.outputs.input_error != 'true'
        run: |
          if git diff --quiet HEAD -- ${{ steps.create-file.outputs.filename}}; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: create PR 
        if: steps.diff.outputs.changed == 'true' && steps.check-issues.outputs.input_error != 'true'
        run: | 
          branch="update-metadata-#${{ github.event.issue.number }}"
          git checkout -b "$branch"
          
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git add *.cfg
          git commit -m "New workflow metadata file added from issue #${{ github.event.issue.number }}"
          git push origin "$branch"
          
          gh pr create \
            --title "Request to update existing metadata from issue #${{ github.event.issue.number }}" \
            --body "Request to update existing metadata configuration file from issue form:
                    -----------------------------------------------------
                    User: ${{ github.actor }} 
                    Issue title: ${{ github.event.issue.title }}
                    Issue ID: ${{ github.event.issue.number }}
                    Filename: ${{ steps.create-file.outputs.filename }}"  \
            --base main \
            --head $(git rev-parse --abbrev-ref HEAD)

          gh issue comment "$NUMBER" --body "$BODY"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            A different version of this metadata file already exists, you can view the existing file here: 
            [${{ steps.create-file.outputs.filename }}](https://github.com/UKNCSP/CDDS-simulation-metadata/tree/main/${{ steps.create-file.outputs.filename }}).

            A pull request has been opened to review your changes.
            
            Please do NOT merge this pull request without review from a CDDS team member.

            Thank you for your contribution.
        
      - name: notify user of duplicate and close issue
        if: steps.diff.outputs.changed == 'false' && steps.check-issues.outputs.input_error != 'true'
        run: |
          gh issue comment "$ISSUE" --body "$BODY"
          gh issue close --repo "$REPO" --comment "Closing issue $ISSUE" "$ISSUE"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ISSUE: ${{ github.event.issue.number }}
          BODY: >
            This metadata file already exists, you can view the existing file here: 
            [${{ steps.create-file.outputs.filename }}](https://github.com/UKNCSP/CDDS-simulation-metadata/tree/main/${{ steps.create-file.outputs.filename }}).

            Thank you for your contribution.
